"""Make .tar.gz archives of example data

For the bfsongrepo data I did the following:
1. run this (from ``vak``)
```console
!curl -sSL https://raw.githubusercontent.com/vocalpy/vak/main/src/scripts/download_autoannotate_data.py | python3 -
```
2. Take the first ~ten .wav files from 022212

For the Jourjine et al. 2023 data I used the clips in ./tests/data-for-tests/source.
Those are generated by a script in ./tests/scripts/generate_ava_segment_test_data.
"""
import pathlib
import tarfile

import vocalpy as voc


def tar_source_data_subdir(dataset_root,
                           tar_dst,
                           archive_name,
                           ext='wav',
                           dry_run=False,
                           skip_exists=False):
    dataset_root = pathlib.Path(dataset_root).expanduser().resolve()
    if not dataset_root.exists():
        raise NotADirectoryError(
            f'Dataset root not found: {dataset_root}'
        )
    tar_dst = pathlib.Path(tar_dst).expanduser().resolve()
    if not tar_dst.exists():
        raise NotADirectoryError(
            f'.tar destination root not found: {tar_dst}'
        )

    archive_path = tar_dst / f"{archive_name}.tar.gz"
    print(
        f'will create archive: {archive_path}'
    )

    if not dry_run:
        if skip_exists:
            if archive_path.exists():
                print('Archive exists already, skipping.')
                return

        paths = voc.paths.from_dir(dataset_root, ext)
        tar = tarfile.open(archive_path, 'w:gz')
        try:
            print("Adding files to archive.")
            for path in paths:
                print(
                    f'Adding: {path.name}'
                )
                arcname = str(path).replace(str(dataset_root) + '/', '')
                tar.add(name=path, arcname=arcname)
        finally:
            tar.close()


HERE = pathlib.Path(__file__).parent
REPO_ROOT = HERE / '..' / '..'
SOURCE_DATA_ROOT = REPO_ROOT / 'tests/data-for-tests/source'
BFSONGREPO_ROOT = REPO_ROOT / "bfsongrepo"
DIRS_TO_TAR_EXT_ARCHIVE_NAME = [
    (BFSONGREPO_ROOT, '.wav', 'bfsongrepo'),
    (SOURCE_DATA_ROOT / 'jourjine-et-al-2023/developmentLL', '.wav', 'jourjine-et-al-2023'),
]
TAR_DST = HERE / 'example_data'


def main():
    for dataset_dir, ext, archive_name in DIRS_TO_TAR_EXT_ARCHIVE_NAME:
        tar_source_data_subdir(dataset_dir, TAR_DST, archive_name, ext)


main()
